```{r message=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggbiplot)
```


```{r}
mtcars.pca <- prcomp(mtcars[,c(1:7,10,11)], center = TRUE,scale. = TRUE)
```

```{r}
summary(mtcars.pca)
```

```{r message = FALSE}
ggbiplot(mtcars.pca)
```

```{r}
ggbiplot(mtcars.pca, labels=rownames(mtcars))
```
```{r}
mtcars.country <- c(rep("Japan", 3), rep("US",4), rep("Europe", 7),rep("US",3), "Europe", rep("Japan", 3), rep("US",4), rep("Europe", 3), "US", rep("Europe", 3))

ggbiplot(mtcars.pca,ellipse=TRUE,  labels=rownames(mtcars), groups=mtcars.country)
```

```{r}
demo_data = demographic_refined.2
```

```{r}
demo_data = demo_data %>%
  mutate(label = if_else(median_household_income >= 100000,"High",
                         if_else(median_household_income >= 75000, "Medium_High",
                                 if_else(median_household_income >= 50000, "Medium_Low", "Low"))))
```

```{r}
demo_data.pca = prcomp(demo_data[,c(5,6,8:33)], center = TRUE,scale. = TRUE)
```

```{r}
summary(demo_data.pca)
```

```{r}
ggbiplot(demo_data.pca)
```



```{r}
labels = unlist(demo_data[34])
ggbiplot(demo_data.pca, ellipse=TRUE, var.axes = FALSE, groups=labels)
```
```{r}
ggbiplot()
```

















